<?php

declare(strict_types=1);

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class DeletedOrder extends Model
{
    public $timestamps = false;
    
    public $incrementing = false;

    protected $casts = [
        'id_company' => 'integer',
        'id_status' => 'integer',
        'cid' => 'integer',
        'lastMaintainID' => 'integer',
        'paid' => 'float',
        'staffid' => 'integer',
        'total' => 'float',
        'direct' => 'integer',
        'delOrder' => 'integer',
        'proforma' => 'integer',
        'showVat' => 'integer',
        'showNotes' => 'integer',
        'vatAmount' => 'float',
        'zeroVat' => 'integer',
        'tx' => 'integer',
        'agentPaid' => 'integer',
        'agentOwed' => 'float',
        'rate' => 'float',
        'txt' => 'integer',
        'aftersales' => 'integer',
        'done' => 'integer',
        'notLoaded' => 'integer',
        'p' => 'integer',
        'wes' => 'integer',
        'colOrder' => 'integer',
        'colID' => 'integer',
        'delID' => 'integer',
        'amzShipped' => 'integer',
        'refund' => 'integer',
        'post' => 'integer',
        'wholeError' => 'integer',
        'mfError' => 'integer',
        'feedbackScore' => 'integer',
        'delissue' => 'integer',
        'defects' => 'integer',
        'oos' => 'integer',
        'mgmt' => 'integer',
        'processed' => 'integer',
        'paidBeds' => 'integer',
        'refundBox' => 'integer',
        'id_delivery_route' => 'integer',
        'id_order_type' => 'integer',
        'id_payment_type' => 'integer',
        'hold' => 'integer',
        'missed' => 'integer',
        'urgent' => 'integer',
        'retention' => 'integer',
        'paypal' => 'integer',
        'reopen' => 'integer',
        'id_supplier' => 'integer',
        'paid_supplier' => 'integer',
        'invoice_made' => 'integer',
        'id_seller' => 'integer',
        'seller_paid' => 'integer',
        'discount_amount' => 'decimal:2',
        'discount_rate' => 'decimal:2',
        'vat_paid' => 'decimal:2',
        'to_collect' => 'integer',
        'is_split' => 'integer',
        'is_shipped' => 'integer',
        'paid_courier' => 'integer',
        'is_collected' => 'integer',
        'escalate' => 'integer',
        'ordered' => 'integer',
        'trust_pilot' => 'integer',
        'stolen' => 'integer',
        'tuffnells' => 'boolean',
        'priority' => 'boolean',
        'manual_order' => 'boolean',
        'delivery_issue' => 'integer',
        'time_stamp' => 'datetime'
    ];

    protected $fillable = [
        'id_company',
        'id_status',
        'cid',
        'delRoute',
        'endDate',
        'endTime',
        'lastMaintainer',
        'lastMaintainID',
        'orderStatus',
        'paid',
        'startDate',
        'startTime',
        'staffName',
        'staffid',
        'total',
        'dispatchType',
        'collector',
        'colDelDate',
        'carrier',
        'orderType',
        'direct',
        'paymentType',
        'delOrder',
        'authNo',
        'cardNo',
        'exp',
        'companyName',
        'ouref',
        'proforma',
        'showVat',
        'showNotes',
        'serType',
        'icType',
        'iNo',
        'ebayID',
        'vatAmount',
        'zeroVat',
        'ebayStatus',
        'deliverBy',
        'tx',
        'delTime',
        'delStat',
        'agent',
        'agentPaid',
        'agentOwed',
        'rate',
        'txt',
        'code',
        'parcelid',
        'neighbour',
        'aftersales',
        'safePlace',
        'done',
        'ebay',
        'notLoaded',
        'p',
        'wes',
        'cStatus',
        'colOrder',
        'colTime',
        'colRoute',
        'extra',
        'beds',
        'delDate',
        'colID',
        'delID',
        'lat',
        'lng',
        'amazonID',
        'amzShipped',
        'refund',
        'postLoc',
        'post',
        'sender',
        'stamp',
        'startStamp',
        'wholeError',
        'mfError',
        'feedbackScore',
        'delissue',
        'defects',
        'g_id',
        'g_num',
        'g_desc',
        'g_ship',
        'oos',
        'mgmt',
        'processed',
        'paidBeds',
        'pTime',
        'refundBox',
        'id_delivery_route',
        'id_order_type',
        'id_payment_type',
        'hold',
        'missed',
        'urgent',
        'retention',
        'paypal',
        'reopen',
        'id_supplier',
        'paid_supplier',
        'invoice_made',
        'id_seller',
        'seller_paid',
        'discount_amount',
        'discount_rate',
        'vat_paid',
        'paypal_payment',
        'last_trans_id',
        'to_collect',
        'is_split',
        'voucher_code',
        'is_shipped',
        'paid_courier',
        'tnt_consignment',
        'ajfoams_tracking_number',
        'bedtatstic_tracking_number',
        'is_collected',
        'escalate',
        'ordered',
        'merch_ref',
        'trust_pilot',
        'stolen',
        'tuffnells',
        'order_number_part_0',
        'order_number_part_1',
        'order_number_part_2',
        'order_number_part_3',
        'order_number_part_4',
        'sales_record',
        'priority',
        'manual_order',
        'delivery_issue'
    ];

    public function company(): BelongsTo
    {
        return $this->belongsTo(Company::class, 'id_company');
    }

    public function supplier(): BelongsTo
    {
        return $this->belongsTo(Supplier::class, 'id_supplier');
    }

    public function seller(): BelongsTo
    {
        return $this->belongsTo(Seller::class, 'id_seller');
    }
} 